# Name of the website
title: KoL Scripting Resources

# Description of the website
description: A grand array of resources for Junior Associate Loathing Engineer Newbies

# Don't give a download link. Nobody needs this.
show_downloads: false

# Your name to show in the footer
author: L. A. S. S.

remote_theme: pages-themes/minimal@v0.2.0

# the actual url
url: https://loathing-associates-scripting-society.github.io/

# the base URL string
baseurl: "KoL-Scripting-Resources"

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
