# Name of the website
title: KoL Scripting Resources

# Description of the website
description: A grand array of resources for Junior Associate Loathing Engineer Newbies

# Don't give a download link. Nobody needs this.
show_downloads: false

# Your name to show in the footer
author: L. A. S. S.

# Navbar links
nav:
  CS Scripts: "CS-Scripting-Resources.md"
  Resources:
    - LASS Homepage: "https://github.com/Loathing-Associates-Scripting-Society"
    - Latest Mafia Build: "https://ci.kolmafia.us/job/Kolmafia/"

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one